module.exports = {
  testMatch: ['**/?(*.)test.js?(x)'],
  roots: ['<rootDir>'],
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
  },
  coverageDirectory: './coverage/',
  collectCoverage: true,
  coverageReporters: ['lcov', 'text'],
  collectCoverageFrom: [
    '!**/.docs/**',
    '!**/.mock/**',
    '!**/.storybook/**',
    '!**/.storybook-static-develop/**',
    '!**/.storybook-static-release/**',
    '!**/coverage/**',
    '!**/node_modules/**',
    'packages/**/*.{js,jsx}',
    '!packages/**/index.js',
    '!packages/**/*.part.js',
    '!packages/**/*.prop.js',
    '!packages/**/*.render*.js',
    '!packages/**/*.story.js',
    '!packages/**/*.test.js',
    '!packages/**/build/**',
    '!packages/**/node_modules/**',
    '!packages/**/webpack*',
    '!packages/components/src/concept/**',
    '!packages/components/src/content/**',
    '!packages/library/**/a11y/**',
    '!packages/library/**/array/**',
    '!packages/library/**/boolean/**',
    '!packages/library/**/browser/**',
    '!packages/library/**/date/**',
    '!packages/library/**/environment/**',
    '!packages/library/**/event/**',
    '!packages/library/**/hooks/**',
    '!packages/library/**/number/**',
    '!packages/library/**/object/**',
    '!packages/library/**/pagination/**',
    '!packages/library/**/sort/**',
    '!packages/library/**/store/**',
    '!packages/library/**/string/**',
    '!packages/docs/**',
    '!packages/styleguide/**',
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|md)$': '<rootDir>/.mock/file.js',
    '^.+\\.(css|less|scss|md)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: ['js', 'jsx'],
  coverageThreshold: {
    global: {
      statements: 88,
      branches: 68,
      functions: 82,
      lines: 87,
    },
  },
}
