#!/bin/bash

npm un -S @papillonads/components @papillonads/library classnames prop-types react react-axe react-copy-to-clipboard react-dom react-redux react-router react-router-dom react-transition-group redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm un -D @babel/cli @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @storybook/addon-a11y @storybook/addon-actions @storybook/addon-info @storybook/addon-knobs @storybook/addon-links @storybook/addon-notes @storybook/addon-storysource @storybook/addons @storybook/react @storybook/theming @svgr/webpack acorn acorn-dynamic-import babel-core babel-eslint babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets clean-webpack-plugin codecov cors css-loader dotenv dotenv-webpack enzyme enzyme-adapter-react-16 eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks file-loader gh-pages git-rev-sync glob-all html-webpack-externals-plugin html-webpack-plugin html-webpack-root-plugin husky identity-obj-proxy ignore-loader imagemin imagemin-gifsicle imagemin-mozjpeg imagemin-optipng imagemin-svgo imagemin-webp imagemin-webp-webpack-plugin img-loader jest jest-axe jest-enzyme lerna lint-staged mini-css-extract-plugin moment node-sass npm-run-all optimize-css-assets-webpack-plugin postcss-loader postcss-preset-env postcss-scss prettier react-test-renderer regenerator-runtime sass-loader storybook-addon-jsx style-loader stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss terser-webpack-plugin webpack webpack-bundle-analyzer webpack-cli webpack-manifest-plugin webpack-merge

npm i -S @papillonads/components @papillonads/library classnames prop-types react react-axe react-copy-to-clipboard react-dom react-redux react-router react-router-dom react-transition-group redux redux-logger redux-mock-store redux-thunk uuid whatwg-fetch

npm i -D @babel/cli @babel/core @babel/plugin-proposal-class-properties @babel/plugin-proposal-object-rest-spread @babel/plugin-proposal-optional-catch-binding @babel/plugin-proposal-optional-chaining @babel/plugin-syntax-dynamic-import @babel/plugin-transform-classes @babel/plugin-transform-runtime @babel/plugin-transform-spread @babel/preset-env @babel/preset-react @babel/register @babel/runtime @storybook/addon-a11y @storybook/addon-actions @storybook/addon-info @storybook/addon-knobs @storybook/addon-links @storybook/addon-notes @storybook/addon-storysource @storybook/addons @storybook/react @storybook/theming @svgr/webpack acorn acorn-dynamic-import babel-core@^7.0.0-bridge.0 babel-eslint babel-jest babel-loader babel-plugin-css-modules-transform babel-plugin-syntax-async-functions babel-plugin-transform-assets clean-webpack-plugin codecov cors css-loader@^3.6.0 dotenv dotenv-webpack enzyme enzyme-adapter-react-16 eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-plugin-prettier eslint-plugin-react eslint-plugin-react-hooks file-loader gh-pages git-rev-sync glob-all html-webpack-externals-plugin html-webpack-plugin@^3.2.0 html-webpack-root-plugin husky identity-obj-proxy ignore-loader imagemin imagemin-gifsicle imagemin-mozjpeg imagemin-optipng imagemin-svgo imagemin-webp imagemin-webp-webpack-plugin img-loader jest jest-axe jest-enzyme lerna lint-staged mini-css-extract-plugin moment node-sass npm-run-all optimize-css-assets-webpack-plugin postcss-loader postcss-preset-env postcss-scss prettier react-test-renderer regenerator-runtime sass-loader storybook-addon-jsx style-loader stylelint stylelint-config-prettier stylelint-config-standard stylelint-order stylelint-prettier stylelint-scss terser-webpack-plugin webpack webpack-bundle-analyzer webpack-cli webpack-manifest-plugin webpack-merge

npm run clean-up && npm run install-packages && npm audit fix && npm run bootstrap

